server:
  port: 8097

spring:
  application:
    name: booking-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/v1/client/**
            - Path=/v1/record/**