server:
  port: 8097

spring:
  application:
    name: booking-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/v1/client/**
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s