server:
  port: 8097

spring:
  application:
    name: booking-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/v1/client/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookingServiceCircuitBreaker
                    fallbackUri: forward:/fallback
            - id: booking-provider-service
              uri: lb://booking-provider-service
              predicates:
                - Path=/v1/provider/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookingProviderServiceCircuitBreaker
                    fallbackUri: forward:/fallback
          httpclient:
            connect-timeout: 3000
            response-timeout: 5s
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET, POST
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 300ms
                  maxBackoff: 3000ms
                  factor: 2
                  basedOnPreviousValue: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: time_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 5s
    instances:
      bookingServiceCircuitBreaker:
        base-config: default
      bookingProviderServiceCircuitBreaker:
        base-config: default